## Importing the basic libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading the dataset and splitting into the dependent and independent variables

In [2]:
dataset = pd.read_excel("Dataset 6 145.xlsx")

feature_names = dataset.columns[:-2]

X = dataset.iloc[:, :-2]
y = dataset.iloc[:, -2]

## Checking the dependent variable

In [3]:
print(y.head)
print(y.describe())

<bound method NDFrame.head of 0      3
1      3
2      3
3      1
4      1
      ..
140    0
141    0
142    0
143    0
144    0
Name: GRADING OF PERIODONTITIS, Length: 145, dtype: int64>
count    145.000000
mean       1.165517
std        1.178593
min        0.000000
25%        0.000000
50%        1.000000
75%        2.000000
max        3.000000
Name: GRADING OF PERIODONTITIS, dtype: float64


## Training and Testing data split

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


## Feature scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


## Dimensionality Reduction

In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
component_weights = pca.components_

## Extracting the important feature names

In [7]:
feature_weights_mapping = {}
for i, component in enumerate(component_weights):
    component_feature_weights = zip(feature_names, component)
    sorted_feature_weights = sorted(
        component_feature_weights, key=lambda x: abs(x[1]), reverse=True
    )
    feature_weights_mapping[f"Component {i+1}"] = sorted_feature_weights
print("Feature names contributing to Principal Components:")
for component, weights in feature_weights_mapping.items():
    print(f"{component}:")
    for feature, weight in weights[:5]:
        print(f"  {feature}: {weight:.4f}")
    print()


Feature names contributing to Principal Components:
Component 1:
  BCAL 32: 0.1120
  MCAL 32: 0.1088
  PCAL 21: 0.1087
  LCAL 32: 0.1085
  DPD 32: 0.1084

Component 2:
  LCAL 37: 0.1191
  LPD 37: 0.1186
  MCAL 15: 0.1081
  MPD 15: 0.1080
  PCAL 15: 0.1073

Component 3:
  BPD 31: 0.1316
  LPD 31: 0.1308
  DPD 31: 0.1293
  LCAL 31: 0.1272
  MPD 31: 0.1265

Component 4:
  LCAL 33: 0.1482
  BPD 33: 0.1387
  PPD 11: -0.1385
  MCAL 33: 0.1355
  LPD 33: 0.1350

Component 5:
  MCAL 24: 0.1542
  DCAL 24: 0.1513
  PPD 24: 0.1371
  BPD 24: 0.1368
  PCAL 24: 0.1332

Component 6:
  BCAL 37: 0.1495
  DPD 37: 0.1493
  MCAL 37: 0.1471
  DCAL 37: 0.1469
  MPD 37: 0.1460

Component 7:
  LPD 45: 0.1725
  BPD 45: 0.1696
  BCAL 45: 0.1681
  LCAL 45: 0.1646
  MCAL 45: 0.1638

Component 8:
  BPD 16: 0.1951
  PPD 16: 0.1946
  BCAL 16: 0.1925
  MPD 16: 0.1918
  MCAL 16: 0.1866

Component 9:
  LCAL 35: 0.1629
  LPD 35: 0.1520
  BCAL 27: -0.1515
  MCAL 27: -0.1501
  BPD 35: 0.1493

Component 10:
  MPD 13: 0.2089

## Random Forest Classifier

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[52  0  0  0]
 [ 0 13  0  0]
 [ 0  0 29  0]
 [ 0  0  2 20]]
0.9827586206896551
Testing Accuracy:
[[12  0  1  0]
 [ 2  1  0  0]
 [ 0  1  7  2]
 [ 0  0  1  2]]
0.7586206896551724


## Decision Tree

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[52  0  0  0]
 [ 0 13  0  0]
 [ 0  0 29  0]
 [ 0  0  0 22]]
1.0
Testing Accuracy:
[[9 3 1 0]
 [0 2 1 0]
 [0 2 6 2]
 [0 0 1 2]]
0.6551724137931034


## Support Vector Machine

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[50  0  2  0]
 [ 2  6  5  0]
 [ 2  1 24  2]
 [ 0  2  8 12]]
0.7931034482758621
Testing Accuracy:
[[13  0  0  0]
 [ 1  1  0  1]
 [ 0  3  7  0]
 [ 0  1  2  0]]
0.7241379310344828


## Kernel SVM

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))



Training Accuracy:
[[51  0  1  0]
 [ 9  3  1  0]
 [ 4  0 25  0]
 [ 4  0 10  8]]
0.75
Testing Accuracy:
[[12  0  1  0]
 [ 3  0  0  0]
 [ 3  0  6  1]
 [ 0  0  1  2]]
0.6896551724137931


## K-Nearest Neighbors

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[51  0  1  0]
 [ 6  1  4  2]
 [ 5  1 21  2]
 [ 2  2  5 13]]
0.7413793103448276
Testing Accuracy:
[[13  0  0  0]
 [ 3  0  0  0]
 [ 2  0  6  2]
 [ 2  0  1  0]]
0.6551724137931034


## Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[49  0  3  0]
 [ 4  4  5  0]
 [ 1  1 23  4]
 [ 0  1 10 11]]
0.75
Testing Accuracy:
[[13  0  0  0]
 [ 2  1  0  0]
 [ 1  2  6  1]
 [ 0  1  2  0]]
0.6896551724137931


## Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[46  1  5  0]
 [ 8  5  0  0]
 [ 9  2 16  2]
 [ 7  1  9  5]]
0.6206896551724138
Testing Accuracy:
[[11  0  2  0]
 [ 3  0  0  0]
 [ 5  1  4  0]
 [ 1  0  2  0]]
0.5172413793103449


## XGBoost

In [15]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[52  0  0  0]
 [ 0 13  0  0]
 [ 0  0 29  0]
 [ 0  0  0 22]]
1.0
Testing Accuracy:
[[12  0  1  0]
 [ 1  2  0  0]
 [ 0  2  6  2]
 [ 0  0  1  2]]
0.7586206896551724


## CatBoost

In [16]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Learning rate set to 0.070894
0:	learn: 1.3354462	total: 151ms	remaining: 2m 31s
1:	learn: 1.2822335	total: 161ms	remaining: 1m 20s
2:	learn: 1.2505513	total: 169ms	remaining: 56.2s
3:	learn: 1.2208318	total: 176ms	remaining: 43.8s
4:	learn: 1.1811526	total: 181ms	remaining: 36.1s
5:	learn: 1.1490911	total: 188ms	remaining: 31.1s
6:	learn: 1.1229990	total: 195ms	remaining: 27.6s
7:	learn: 1.0929716	total: 201ms	remaining: 24.9s
8:	learn: 1.0681855	total: 206ms	remaining: 22.7s
9:	learn: 1.0459284	total: 211ms	remaining: 20.9s
10:	learn: 1.0273464	total: 216ms	remaining: 19.4s
11:	learn: 1.0074057	total: 220ms	remaining: 18.1s
12:	learn: 0.9853722	total: 224ms	remaining: 17s
13:	learn: 0.9631558	total: 228ms	remaining: 16s
14:	learn: 0.9426569	total: 231ms	remaining: 15.2s
15:	learn: 0.9234098	total: 235ms	remaining: 14.4s
16:	learn: 0.9072919	total: 238ms	remaining: 13.7s
17:	learn: 0.8932027	total: 240ms	remaining: 13.1s
18:	learn: 0.8759986	total: 244ms	remaining: 12.6s
19:	learn: 0.

# ANN

In [17]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dropout(rate=0.2))
ann.add(tf.keras.layers.Dense(units=4, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1) 
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_classes)
print(cm)
print(accuracy_score(y_test, y_pred_classes))
for i in range(4):
    print(f"\nClass {i}:")
    tn, fp, fn, tp = confusion_matrix((y_test == i), (y_pred_classes == i)).ravel()
    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0
    print(f"Sensitivity: {sensitivity:.4f}")
    print(f"Specificity: {specificity:.4f}")

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.1597 - loss: 2.6878
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1233 - loss: 2.6622 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.1739 - loss: 2.3235 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0931 - loss: 2.3321 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1295 - loss: 2.0728 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1420 - loss: 1.9476 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1856 - loss: 1.7079 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1949 - loss: 1.7339 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2060 - loss: 1.6134 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.1523 - loss: 1.6468 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2916 - loss: 1.5944 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3571 - loss