## Importing the basic libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading the dataset and splitting into the dependent and independent variables

In [2]:
dataset = pd.read_excel("Dataset 6 186.xlsx")

feature_names = dataset.columns[:-2]

X = dataset.iloc[:, :-2]
y = dataset.iloc[:, -2]
print(feature_names)

Index(['AGE', 'SEX', 'ORAL HABITS', 'bleeding/ swollen gums ',
       'food enlodgement +pain ', 'pain during chewing', 'tooth mobility',
       '           bad odor', 'others(non periodontal reasons)',
       'brushing habits',
       ...
       'BPD 47', 'BCAL 47', 'DPD 47', 'DCAL 47', 'LPD 47', 'LCAL 47',
       'DIABETES ASSESSMENT', 'GINGIVITIS', 'PERIODONTITIS',
       'STAGING OF PERIODONTITIS'],
      dtype='object', length=249)


## Checking the dependent variable

In [3]:
print(y.head)
print(y.describe())

<bound method NDFrame.head of 0      3
1      3
2      3
3      1
4      1
      ..
195    2
196    2
197    2
198    2
199    0
Name: GRADING OF PERIODONTITIS, Length: 200, dtype: int64>
count    200.0000
mean       1.1750
std        1.1838
min        0.0000
25%        0.0000
50%        1.0000
75%        2.0000
max        3.0000
Name: GRADING OF PERIODONTITIS, dtype: float64


## Training and Testing data split

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


## Feature scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


## Dimensionality Reduction

In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
component_weights = pca.components_

## Extracting the important feature names

In [7]:
feature_weights_mapping = {}
for i, component in enumerate(component_weights):
    component_feature_weights = zip(feature_names, component)
    sorted_feature_weights = sorted(
        component_feature_weights, key=lambda x: abs(x[1]), reverse=True
    )
    feature_weights_mapping[f"Component {i+1}"] = sorted_feature_weights
print("Feature names contributing to Principal Components:")
for component, weights in feature_weights_mapping.items():
    print(f"{component}:")
    for feature, weight in weights[:5]:
        print(f"  {feature}: {weight:.4f}")
    print()


Feature names contributing to Principal Components:
Component 1:
  BCAL 23: 0.1033
  BCAL 32: 0.1027
  MCAL 32: 0.1002
  DCAL 32: 0.1000
  LCAL 32: 0.0987

Component 2:
  ORAL HABITS: 0.1107
  MCAL 15: -0.1050
  PCAL 15: -0.1000
  PPD 15: -0.0993
  BCAL 43: 0.0986

Component 3:
  MPD 33: 0.1520
  LPD 33: 0.1507
  DPD 33: 0.1501
  BPD 33: 0.1501
  MCAL 33: 0.1435

Component 4:
  DPD 31: 0.1390
  MPD 31: 0.1389
  LPD 31: 0.1372
  BPD 31: 0.1370
  BCAL 31: 0.1308

Component 5:
  BPD 14: 0.1520
  PPD 14: 0.1518
  DPD 14: 0.1510
  PCAL 14: 0.1499
  DPD 25: 0.1493

Component 6:
  LCAL 41: 0.1594
  DCAL 41: 0.1576
  MCAL 41: 0.1566
  DPD 41: 0.1552
  BCAL 41: 0.1521

Component 7:
  DPD 24: 0.2181
  MPD 24: 0.2136
  BPD 24: 0.2115
  PPD 24: 0.2110
  PCAL 24: 0.2064

Component 8:
  MCAL 13: 0.1804
  DCAL 13: 0.1788
  PPD 13: 0.1770
  MPD 13: 0.1761
  DPD 13: 0.1754

Component 9:
  LCAL 46: 0.1646
  LPD 47: 0.1554
  DCAL 47: 0.1532
  LCAL 47: 0.1531
  MCAL 47: 0.1525

Component 10:
  MCAL 23: 0.

## Random Forest Classifier

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[76  0  0  0]
 [ 0 13  0  0]
 [ 1  0 45  0]
 [ 0  0  0 25]]
0.99375
Testing Accuracy:
[[13  0  1  1]
 [ 2  0  2  0]
 [ 0  0 10  2]
 [ 0  0  6  3]]
0.65


## Decision Tree

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[76  0  0  0]
 [ 0 13  0  0]
 [ 0  0 46  0]
 [ 0  0  0 25]]
1.0
Testing Accuracy:
[[13  0  1  1]
 [ 1  0  2  1]
 [ 1  2  8  1]
 [ 0  1  6  2]]
0.575


## Support Vector Machine

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[73  0  3  0]
 [ 4  3  6  0]
 [ 5  0 40  1]
 [ 0  0 12 13]]
0.80625
Testing Accuracy:
[[14  1  0  0]
 [ 1  0  2  1]
 [ 0  0 11  1]
 [ 1  0  6  2]]
0.675


## Kernel SVM

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))



Training Accuracy:
[[75  0  1  0]
 [ 8  1  4  0]
 [ 9  0 37  0]
 [ 3  0  9 13]]
0.7875
Testing Accuracy:
[[14  0  1  0]
 [ 1  0  2  1]
 [ 2  0 10  0]
 [ 2  0  7  0]]
0.6


## K-Nearest Neighbors

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[74  0  2  0]
 [ 7  2  4  0]
 [ 6  4 35  1]
 [ 1  0 11 13]]
0.775
Testing Accuracy:
[[14  0  0  1]
 [ 2  0  2  0]
 [ 0  0 10  2]
 [ 2  0  6  1]]
0.625


## Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[73  0  3  0]
 [ 5  2  6  0]
 [ 5  0 40  1]
 [ 0  0 11 14]]
0.80625
Testing Accuracy:
[[14  1  0  0]
 [ 1  0  2  1]
 [ 0  0 11  1]
 [ 1  0  5  3]]
0.7


## Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[67  0  7  2]
 [ 9  1  3  0]
 [24  2 15  5]
 [ 6  0  9 10]]
0.58125
Testing Accuracy:
[[13  0  0  2]
 [ 2  0  2  0]
 [10  0  2  0]
 [ 4  0  3  2]]
0.425


## XGBoost

In [15]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[76  0  0  0]
 [ 0 13  0  0]
 [ 0  0 46  0]
 [ 0  0  0 25]]
1.0
Testing Accuracy:
[[13  0  2  0]
 [ 1  0  2  1]
 [ 0  1 11  0]
 [ 1  0  6  2]]
0.65


## CatBoost

In [16]:
! pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.1 MB/s eta 0:00:00


In [17]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Learning rate set to 0.072066
0:	learn: 1.3258269	total: 52.8ms	remaining: 52.8s
1:	learn: 1.2737901	total: 57.3ms	remaining: 28.6s
2:	learn: 1.2335873	total: 62.3ms	remaining: 20.7s
3:	learn: 1.1995222	total: 66.9ms	remaining: 16.7s
4:	learn: 1.1685545	total: 71.5ms	remaining: 14.2s
5:	learn: 1.1338982	total: 75.8ms	remaining: 12.6s
6:	learn: 1.0965182	total: 80.3ms	remaining: 11.4s
7:	learn: 1.0666597	total: 84.6ms	remaining: 10.5s
8:	learn: 1.0342289	total: 89.1ms	remaining: 9.8s
9:	learn: 1.0071775	total: 98.1ms	remaining: 9.71s
10:	learn: 0.9797051	total: 110ms	remaining: 9.88s
11:	learn: 0.9552581	total: 121ms	remaining: 10s
12:	learn: 0.9297074	total: 127ms	remaining: 9.66s
13:	learn: 0.9054696	total: 132ms	remaining: 9.27s
14:	learn: 0.8870635	total: 136ms	remaining: 8.94s
15:	learn: 0.8650187	total: 141ms	remaining: 8.64s
16:	learn: 0.8478693	total: 145ms	remaining: 8.38s
17:	learn: 0.8324330	total: 149ms	remaining: 8.15s
18:	learn: 0.8150005	total: 154ms	remaining: 7.94s
19:	

# ANN

In [18]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dropout(rate=0.2))
ann.add(tf.keras.layers.Dense(units=4, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_classes)
print(cm)
print(accuracy_score(y_test, y_pred_classes))

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 6s 33ms/step - accuracy: 0.1628 - loss: 1.5526
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3372 - loss: 1.5230 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4356 - loss: 1.4477
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4549 - loss: 1.4934 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.4470 - loss: 1.3900 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4792 - loss: 1.3845 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4705 - loss: 1.3595 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.4234 - loss: 1.3989
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4444 - loss: 1.3332
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4544 - loss: 1.3218
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.4425 - loss: 1.3157
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4812