## Importing the basic libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading the dataset and splitting into the dependent and independent variables

In [2]:
dataset = pd.read_excel("Dataset 6 186.xlsx")

feature_names = dataset.columns[:-2]

X = dataset.iloc[:, :-2]
y = dataset.iloc[:, -2]
print(feature_names)

Index(['AGE', 'SEX', 'ORAL HABITS', 'bleeding/ swollen gums ',
       'food enlodgement +pain ', 'pain during chewing', 'tooth mobility',
       '           bad odor', 'others(non periodontal reasons)',
       'brushing habits',
       ...
       'BPD 47', 'BCAL 47', 'DPD 47', 'DCAL 47', 'LPD 47', 'LCAL 47',
       'DIABETES ASSESSMENT', 'GINGIVITIS', 'PERIODONTITIS',
       'STAGING OF PERIODONTITIS'],
      dtype='object', length=249)


## Checking the dependent variable

In [3]:
print(y.head)
print(y.describe())

<bound method NDFrame.head of 0      3
1      3
2      3
3      1
4      1
      ..
180    0
181    0
182    0
183    0
184    0
Name: GRADING OF PERIODONTITIS, Length: 185, dtype: int64>
count    185.000000
mean       1.189189
std        1.189580
min        0.000000
25%        0.000000
50%        1.000000
75%        2.000000
max        3.000000
Name: GRADING OF PERIODONTITIS, dtype: float64


## Training and Testing data split

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


## Feature scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


## Dimensionality Reduction

In [6]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
component_weights = pca.components_

## Extracting the important feature names

In [7]:
feature_weights_mapping = {}
for i, component in enumerate(component_weights):
    component_feature_weights = zip(feature_names, component)
    sorted_feature_weights = sorted(
        component_feature_weights, key=lambda x: abs(x[1]), reverse=True
    )
    feature_weights_mapping[f"Component {i+1}"] = sorted_feature_weights
print("Feature names contributing to Principal Components:")
for component, weights in feature_weights_mapping.items():
    print(f"{component}:")
    for feature, weight in weights[:5]:
        print(f"  {feature}: {weight:.4f}")
    print()


Feature names contributing to Principal Components:
Component 1:
  BCAL 32: 0.1115
  MCAL 32: 0.1095
  DCAL 32: 0.1089
  LCAL 32: 0.1087
  DPD 32: 0.1068

Component 2:
  LCAL 37: 0.1121
  LPD 37: 0.1118
  MCAL 15: 0.1028
  BPD 26: 0.0986
  MPD 26: 0.0986

Component 3:
  LPD 33: 0.1689
  BPD 33: 0.1680
  DPD 33: 0.1663
  MPD 33: 0.1653
  LCAL 33: 0.1625

Component 4:
  BPD 13: 0.1575
  PCAL 13: 0.1561
  BCAL 13: 0.1552
  DPD 13: 0.1546
  DCAL 13: 0.1530

Component 5:
  PCAL 11: 0.1272
  BPD 11: 0.1249
  DCAL 37: 0.1249
  PPD 11: 0.1231
  BCAL 11: 0.1226

Component 6:
  BCAL 17: 0.1674
  MPD 17: 0.1653
  PPD 17: 0.1652
  BPD 17: 0.1645
  MCAL 17: 0.1633

Component 7:
  BPD 22: 0.1656
  DPD 22: 0.1640
  DCAL 22: 0.1615
  MPD 22: 0.1609
  MCAL 22: 0.1605

Component 8:
  DPD 24: 0.1781
  DCAL 24: 0.1779
  MPD 24: 0.1745
  MCAL 24: 0.1738
  BPD 24: 0.1710

Component 9:
  LCAL 47: 0.1721
  DCAL 47: 0.1719
  DPD 47: 0.1711
  BPD 47: 0.1710
  MPD 47: 0.1707

Component 10:
  BPD 45: 0.1721
  DPD

## Random Forest Classifier

In [8]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0]
 [ 1 14  0  0]
 [ 0  0 42  0]
 [ 0  0  1 26]]
0.9864864864864865
Testing Accuracy:
[[14  0  4  1]
 [ 1  0  1  0]
 [ 0  2  6  2]
 [ 0  1  2  3]]
0.6216216216216216


## Decision Tree

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0]
 [ 0 15  0  0]
 [ 0  0 42  0]
 [ 0  0  0 27]]
1.0
Testing Accuracy:
[[15  0  4  0]
 [ 1  0  1  0]
 [ 3  2  2  3]
 [ 0  1  2  3]]
0.5405405405405406


## Support Vector Machine

In [10]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0]
 [ 3  7  5  0]
 [ 1  2 36  3]
 [ 0  2 14 11]]
0.7972972972972973
Testing Accuracy:
[[16  1  2  0]
 [ 0  0  2  0]
 [ 2  1  6  1]
 [ 0  0  2  4]]
0.7027027027027027


## Kernel SVM

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))



Training Accuracy:
[[62  0  2  0]
 [ 9  3  3  0]
 [ 8  0 34  0]
 [ 4  0 13 10]]
0.7364864864864865
Testing Accuracy:
[[16  0  3  0]
 [ 1  0  1  0]
 [ 3  0  6  1]
 [ 1  0  4  1]]
0.6216216216216216


## K-Nearest Neighbors

In [12]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[61  0  3  0]
 [ 3  8  4  0]
 [ 4  3 29  6]
 [ 2  1 10 14]]
0.7567567567567568
Testing Accuracy:
[[16  0  2  1]
 [ 1  0  1  0]
 [ 4  1  4  1]
 [ 0  1  3  2]]
0.5945945945945946


## Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[63  0  1  0]
 [ 5  4  6  0]
 [ 3  2 34  3]
 [ 0  1 15 11]]
0.7567567567567568
Testing Accuracy:
[[16  1  2  0]
 [ 0  0  2  0]
 [ 1  0  8  1]
 [ 0  0  2  4]]
0.7567567567567568


## Naive Bayes

In [14]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[58  1  3  2]
 [10  0  3  2]
 [22  0 17  3]
 [11  0  8  8]]
0.5608108108108109
Testing Accuracy:
[[15  0  4  0]
 [ 1  0  1  0]
 [ 5  0  4  1]
 [ 1  1  2  2]]
0.5675675675675675


## XGBoost

In [15]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0]
 [ 0 15  0  0]
 [ 0  0 42  0]
 [ 0  0  0 27]]
1.0
Testing Accuracy:
[[16  0  3  0]
 [ 0  0  2  0]
 [ 2  1  3  4]
 [ 0  0  3  3]]
0.5945945945945946


## CatBoost

In [17]:
! pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 9.3 MB/s eta 0:00:00


In [18]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Learning rate set to 0.071781
0:	learn: 1.3274743	total: 61.2ms	remaining: 1m 1s
1:	learn: 1.3004083	total: 74.9ms	remaining: 37.4s
2:	learn: 1.2528312	total: 101ms	remaining: 33.5s
3:	learn: 1.2099429	total: 128ms	remaining: 31.8s
4:	learn: 1.1795274	total: 144ms	remaining: 28.7s
5:	learn: 1.1500953	total: 164ms	remaining: 27.2s
6:	learn: 1.1273685	total: 177ms	remaining: 25.1s
7:	learn: 1.0972641	total: 215ms	remaining: 26.6s
8:	learn: 1.0742177	total: 226ms	remaining: 24.9s
9:	learn: 1.0451899	total: 242ms	remaining: 23.9s
10:	learn: 1.0161431	total: 255ms	remaining: 22.9s
11:	learn: 0.9935774	total: 270ms	remaining: 22.3s
12:	learn: 0.9746894	total: 295ms	remaining: 22.4s
13:	learn: 0.9591511	total: 311ms	remaining: 21.9s
14:	learn: 0.9443131	total: 342ms	remaining: 22.5s
15:	learn: 0.9273106	total: 397ms	remaining: 24.4s
16:	learn: 0.9095862	total: 423ms	remaining: 24.5s
17:	learn: 0.8938395	total: 435ms	remaining: 23.7s
18:	learn: 0.8796280	total: 460ms	remaining: 23.8s
19:	learn

# ANN

In [19]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dropout(rate=0.2))
ann.add(tf.keras.layers.Dense(units=4, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_classes)
print(cm)
print(accuracy_score(y_test, y_pred_classes))

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.1929 - loss: 1.4014
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3263 - loss: 1.3880 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4069 - loss: 1.3751 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4240 - loss: 1.3814  
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4469 - loss: 1.3521 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4465 - loss: 1.3571
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4355 - loss: 1.3398 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4220 - loss: 1.3559
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4308 - loss: 1.3498
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4890 - loss: 1.3310
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4762 - loss: 1.3231
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4960 - l