## Importing the basic libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Reading the dataset and splitting into the dependent and independent variables

In [4]:
dataset = pd.read_excel("Dataset 6 186.xlsx")

feature_names = dataset.columns[:-3]

X = dataset.iloc[:, :-3]
y = dataset.iloc[:, -3]
print(feature_names)

Index(['AGE', 'SEX', 'ORAL HABITS', 'bleeding/ swollen gums ',
       'food enlodgement +pain ', 'pain during chewing', 'tooth mobility',
       '           bad odor', 'others(non periodontal reasons)',
       'brushing habits',
       ...
       'MCAL 47', 'BPD 47', 'BCAL 47', 'DPD 47', 'DCAL 47', 'LPD 47',
       'LCAL 47', 'DIABETES ASSESSMENT', 'GINGIVITIS', 'PERIODONTITIS'],
      dtype='object', length=248)


## Checking the dependent variable

In [5]:
print(y.head)
print(y.describe())

<bound method NDFrame.head of 0      4
1      4
2      4
3      2
4      3
      ..
180    0
181    0
182    0
183    0
184    0
Name: STAGING OF PERIODONTITIS, Length: 185, dtype: int64>
count    185.000000
mean       1.864865
std        1.796164
min        0.000000
25%        0.000000
50%        2.000000
75%        4.000000
max        4.000000
Name: STAGING OF PERIODONTITIS, dtype: float64


## Training and Testing data split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


## Feature scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


## Dimensionality Reduction

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
component_weights = pca.components_

## Extracting the important feature names

In [9]:
feature_weights_mapping = {}
for i, component in enumerate(component_weights):
    component_feature_weights = zip(feature_names, component)
    sorted_feature_weights = sorted(
        component_feature_weights, key=lambda x: abs(x[1]), reverse=True
    )
    feature_weights_mapping[f"Component {i+1}"] = sorted_feature_weights
print("Feature names contributing to Principal Components:")
for component, weights in feature_weights_mapping.items():
    print(f"{component}:")
    for feature, weight in weights[:5]:
        print(f"  {feature}: {weight:.4f}")
    print()


Feature names contributing to Principal Components:
Component 1:
  BCAL 32: 0.1120
  MCAL 32: 0.1101
  DCAL 32: 0.1095
  LCAL 32: 0.1093
  DPD 32: 0.1074

Component 2:
  LCAL 37: 0.1123
  LPD 37: 0.1120
  MCAL 15: 0.1032
  BPD 26: 0.0991
  MPD 26: 0.0991

Component 3:
  LPD 33: 0.1693
  BPD 33: 0.1685
  DPD 33: 0.1665
  MPD 33: 0.1655
  LCAL 33: 0.1629

Component 4:
  BPD 13: 0.1577
  PCAL 13: 0.1563
  BCAL 13: 0.1553
  DPD 13: 0.1548
  DCAL 13: 0.1532

Component 5:
  PCAL 11: 0.1276
  BPD 11: 0.1253
  DCAL 37: 0.1245
  PPD 11: 0.1235
  BCAL 11: 0.1230

Component 6:
  BCAL 17: 0.1673
  MPD 17: 0.1652
  PPD 17: 0.1651
  BPD 17: 0.1644
  MCAL 17: 0.1632

Component 7:
  BPD 22: 0.1646
  DPD 22: 0.1633
  DCAL 22: 0.1609
  MPD 22: 0.1602
  MCAL 22: 0.1599

Component 8:
  DCAL 24: 0.1767
  DPD 24: 0.1765
  MCAL 24: 0.1724
  MPD 24: 0.1723
  BPD 24: 0.1700

Component 9:
  LCAL 47: 0.1722
  DCAL 47: 0.1720
  DPD 47: 0.1712
  BPD 47: 0.1711
  MPD 47: 0.1708

Component 10:
  BPD 45: 0.1739
  DPD

## Random Forest Classifier

In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0  0]
 [ 1  4  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 25  0]
 [ 0  0  0  0 47]]
0.9932432432432432
Testing Accuracy:
[[15  0  0  4]
 [ 0  0  1  0]
 [ 1  0  2  4]
 [ 1  0  3  6]]
0.6216216216216216


## Decision Tree

In [11]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 25  0]
 [ 0  0  0  0 47]]
1.0
Testing Accuracy:
[[13  1  1  1  3]
 [ 0  0  0  0  0]
 [ 0  0  0  1  0]
 [ 0  1  0  3  3]
 [ 1  1  0  3  5]]
0.5675675675675675


## Support Vector Machine

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[63  0  0  1  0]
 [ 1  2  0  2  0]
 [ 4  0  2  0  1]
 [ 2  0  0 19  4]
 [ 1  0  0  5 41]]
0.8581081081081081
Testing Accuracy:
[[17  0  1  1]
 [ 0  0  1  0]
 [ 1  0  3  3]
 [ 1  0  3  6]]
0.7027027027027027


## Kernel SVM

In [13]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))



Training Accuracy:
[[62  0  0  0  2]
 [ 3  1  0  0  1]
 [ 4  0  1  0  2]
 [15  0  0  4  6]
 [ 6  0  0  0 41]]
0.7364864864864865
Testing Accuracy:
[[16  0  0  3]
 [ 1  0  0  0]
 [ 2  0  0  5]
 [ 2  0  1  7]]
0.6216216216216216


## K-Nearest Neighbors

In [14]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[60  0  0  1  3]
 [ 4  0  0  0  1]
 [ 3  0  1  1  2]
 [ 6  0  0 13  6]
 [ 2  0  1  4 40]]
0.7702702702702703
Testing Accuracy:
[[16  0  0  3]
 [ 1  0  0  0]
 [ 3  0  0  4]
 [ 1  0  3  6]]
0.5945945945945946


## Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[63  0  0  0  1]
 [ 1  2  0  2  0]
 [ 4  0  3  0  0]
 [ 3  0  0 19  3]
 [ 1  0  1  3 42]]
0.8716216216216216
Testing Accuracy:
[[16  0  2  1]
 [ 0  0  1  0]
 [ 1  1  1  4]
 [ 0  0  3  7]]
0.6486486486486487


## Naive Bayes

In [16]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[58  0  0  2  4]
 [ 3  2  0  0  0]
 [ 4  0  1  2  0]
 [18  0  1  3  3]
 [18  0  2 12 15]]
0.5337837837837838
Testing Accuracy:
[[15  0  2  2]
 [ 1  0  0  0]
 [ 3  1  1  2]
 [ 4  2  3  1]]
0.4594594594594595


## XGBoost

In [17]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Training Accuracy:
[[64  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0 25  0]
 [ 0  0  0  0 47]]
1.0
Testing Accuracy:
[[16  0  1  2]
 [ 0  0  1  0]
 [ 1  0  1  5]
 [ 0  0  3  7]]
0.6486486486486487


## CatBoost

In [21]:
from catboost import CatBoostClassifier
classifier = CatBoostClassifier()
classifier.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix, accuracy_score
print("Training Accuracy:")
y_pred_train = classifier.predict(X_train)
cm_train = confusion_matrix(y_train, y_pred_train)
print(cm_train)
print(accuracy_score(y_train, y_pred_train))

print("Testing Accuracy:")
y_pred_test = classifier.predict(X_test)
cm_test = confusion_matrix(y_test, y_pred_test)
print(cm_test)
print(accuracy_score(y_test, y_pred_test))


Learning rate set to 0.071781
0:	learn: 1.5478547	total: 54.9ms	remaining: 54.9s
1:	learn: 1.4937465	total: 60.5ms	remaining: 30.2s
2:	learn: 1.4375819	total: 66.2ms	remaining: 22s
3:	learn: 1.3853437	total: 73.1ms	remaining: 18.2s
4:	learn: 1.3434285	total: 79ms	remaining: 15.7s
5:	learn: 1.3066240	total: 91.1ms	remaining: 15.1s
6:	learn: 1.2757905	total: 96.6ms	remaining: 13.7s
7:	learn: 1.2398853	total: 102ms	remaining: 12.6s
8:	learn: 1.2076660	total: 107ms	remaining: 11.8s
9:	learn: 1.1698898	total: 113ms	remaining: 11.2s
10:	learn: 1.1403814	total: 119ms	remaining: 10.7s
11:	learn: 1.1189347	total: 124ms	remaining: 10.2s
12:	learn: 1.0978511	total: 134ms	remaining: 10.2s
13:	learn: 1.0747883	total: 140ms	remaining: 9.89s
14:	learn: 1.0512073	total: 148ms	remaining: 9.72s
15:	learn: 1.0352671	total: 157ms	remaining: 9.68s
16:	learn: 1.0149434	total: 170ms	remaining: 9.85s
17:	learn: 0.9937657	total: 185ms	remaining: 10.1s
18:	learn: 0.9749650	total: 190ms	remaining: 9.83s
19:	lear

In [19]:
! pip install catboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 8.5 MB/s eta 0:00:00


# ANN


In [22]:
import tensorflow as tf
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=8, activation='relu'))
ann.add(tf.keras.layers.Dropout(rate=0.2))
ann.add(tf.keras.layers.Dense(units=5, activation='sigmoid'))
ann.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred_classes)
print(cm)
print(accuracy_score(y_test, y_pred_classes))

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 8s 11ms/step - accuracy: 0.1581 - loss: 2.0573
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2224 - loss: 1.8891
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.1855 - loss: 1.8230
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1593 - loss: 1.7460 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2170 - loss: 1.6208
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2317 - loss: 1.6826 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.1791 - loss: 1.6827 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2697 - loss: 1.6115 
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2937 - loss: 1.5795 
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.2635 - loss: 1.5486  
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3047 - loss: 1.5191  
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.2583 - l